name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the discord bot
      env:
        DISCORD_TOKEN: ${{ secrets.BUILD_TOKEN }}
        CHANNEL_ID: ${{ secrets.BUILD_CHANNEL }}
      run: |
        python main.py

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Connecting to the VM and deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Attach to the screen session and stop main.py
            screen -S asdos -X quit
            
            # Navigate to the codebase directory (update this path)
            cd ~/asdos/AsdosBot
            
            # Update the codebase
            git pull
            
            # Restart the python program in screen
            screen -dmS asdos python3 main.py